### PR TITLE
(12123) Newsletter Signup

### PR DESCRIPTION
**Pull request by adammade**
https://mademedia.freshdesk.com/helpdesk/tickets/12123

Screencast of the it here:
http://recordit.co/O4MOyvPaeZ

### CODE REVIEW

**Comment by adammade** [comment]
Only thing I saw in the tempaltes was this: Which I knocked together, not really a logo.

screen shot 2017-07-31 at 11 21 28

**Comment by davidrapson** [comment]
This is what was on the test email that was sent out: screen shot 2017-07-31 at 11 22 28

**Comment by stef-grindley** [comment]
Aye, that's the one!

**Comment by adammade** [comment]
screen shot 2017-08-01 at 10 27 24

Made Up logo added

**Pull request merged**
